from enum import Enum


class BuildingBlockType(Enum):
    TECHNICAL_MODULE = 'TECHNICAL_MODULE'
    ENVIRONMENTAL_MODULE = 'ENVIRONMENTAL_MODULE'
    DEMAND_MODULE = 'DEMAND_MODULE'
    LEGAL_MODULE = 'LEGAL_MODULE'
    HR_MODULE = 'HR_MODULE'
