from enum import Enum


class MEOutputStatus(Enum):
    ON_TRACK = 'ON_TRACK'
    COMPLETED = 'COMPLETED'
    DELAYED = 'DELAYED'
    SATISFACTORY = 'SATISFACTORY'
    NOT_SATISFACTORY = 'NOT_SATISFACTORY'
    MODERATELY_SATISFACTORY = 'MODERATELY_SATISFACTORY'
    NO_ASSESSMENT = 'NO_ASSESSMENT'
