from enum import Enum


class ProjectAction(Enum):
    CREATE = 'CREATE'
    SUBMIT = 'SUBMIT'
    APPROVE = 'APPROVE'
    CONDITIONALLY_APPROVE = 'CONDITIONALLY_APPROVE'
    REVISE = 'REVISE'
    REJECT = 'REJECT'
    REVERT = 'REVERT'
    ASSIGN = 'ASSIGN'
    COMPLETE = 'COMPLETE'
    ALLOCATE_FUNDS = 'ALLOCATE_FUNDS'
    SUSPEND = 'SUSPEND'
