"""empty message

Revision ID: 01d003783a38
Revises: f67bed7b31ec
Create Date: 2021-04-07 21:28:07.828017

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01d003783a38'
down_revision = 'f67bed7b31ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column(
        'output_ids', sa.JSON(), nullable=False))
    op.drop_constraint('activity_output_id_ibfk',
                       'activity', type_='foreignkey')
    op.drop_column('activity', 'output_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('output_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('activity_output_id_ibfk',
                          'activity', 'output', ['output_id'], ['id'])
    op.drop_column('activity', 'output_ids')
    # ### end Alembic commands ###
