"""empty message

Revision ID: 03fe98e02a5c
Revises: 7efc17ba1cdd
Create Date: 2020-09-17 00:41:13.868310

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03fe98e02a5c'
down_revision = '7efc17ba1cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE workflow SET phases = '[]'")
    op.alter_column('workflow', 'phases',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.JSON(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow', 'phases',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=20),
                    nullable=False,
                    existing_server_default=sa.text("'*'"))
    # ### end Alembic commands ###
