"""empty message

Revision ID: 04f063d4d26f
Revises: 493577d9455f
Create Date: 2021-04-08 00:39:27.376650

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04f063d4d26f'
down_revision = '493577d9455f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicator', 'baseline',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.String(length=100),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicator', 'baseline',
                    existing_type=sa.String(length=100),
                    type_=mysql.VARCHAR(length=20),
                    existing_nullable=False)
    # ### end Alembic commands ###
