"""empty message

Revision ID: 0734b1d10ef7
Revises: 04f063d4d26f
Create Date: 2021-04-08 02:02:45.860670

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0734b1d10ef7'
down_revision = '04f063d4d26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('output', 'output_value',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('output', 'output_value',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    # ### end Alembic commands ###
