"""empty message

Revision ID: 0a10f52358f1
Revises: d42ffb67c70f
Create Date: 2021-04-12 21:21:01.558524

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a10f52358f1'
down_revision = 'd42ffb67c70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    existing_nullable=False)
    op.alter_column('project', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    existing_nullable=False)
    op.alter_column('timeline', 'project_action',
                    existing_type=mysql.ENUM('CREATE', 'SUBMIT', 'APPROVE', 'REVISE', 'REJECT', 'ASSIGN', 'COMPLETE',
                                             'ALLOCATE_FUNDS', 'SUSPEND', 'REVERT', charset='utf8', collation='utf8_general_ci'),
                    type_=sa.Enum('CREATE', 'SUBMIT', 'APPROVE', 'CONDITIONALLY_APPROVE', 'REVISE', 'REJECT',
                                  'REVERT', 'ASSIGN', 'COMPLETE', 'ALLOCATE_FUNDS', 'SUSPEND', name='projectaction'),
                    existing_nullable=False)
    op.alter_column('workflow', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow', 'project_status',
                    existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED',
                                          'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    type_=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                     'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    existing_nullable=True)
    op.alter_column('timeline', 'project_action',
                    existing_type=sa.Enum('CREATE', 'SUBMIT', 'APPROVE', 'CONDITIONALLY_APPROVE', 'REVISE', 'REJECT',
                                          'REVERT', 'ASSIGN', 'COMPLETE', 'ALLOCATE_FUNDS', 'SUSPEND', name='projectaction'),
                    type_=mysql.ENUM('CREATE', 'SUBMIT', 'APPROVE', 'REVISE', 'REJECT', 'ASSIGN', 'COMPLETE',
                                     'ALLOCATE_FUNDS', 'SUSPEND', 'REVERT', charset='utf8', collation='utf8_general_ci'),
                    existing_nullable=False)
    op.alter_column('project', 'project_status',
                    existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED',
                                          'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    type_=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                     'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    existing_nullable=False)
    op.alter_column('notification', 'project_status',
                    existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'CONDITIONALLY_APPROVED', 'REVISED', 'REJECTED',
                                          'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'IN_PIPELINE', 'POST_EVALUATION', name='projectstatus'),
                    type_=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                     'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    existing_nullable=False)
    # ### end Alembic commands ###
