"""empty message

Revision ID: 0ad6be19b8a9
Revises: 85f40c04742b
Create Date: 2021-03-13 23:09:46.974137

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad6be19b8a9'
down_revision = '85f40c04742b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'ndp_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'ndp_number')
    # ### end Alembic commands ###
