"""empty message

Revision ID: 0cf1b024c3ba
Revises: 9fcf492158e8
Create Date: 2020-08-22 21:56:09.230321

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cf1b024c3ba'
down_revision = '9fcf492158e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'role', sa.String(length=50), nullable=False))
    op.drop_column('workflow', 'role_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'role_key', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('workflow', 'role')
    # ### end Alembic commands ###
