"""empty message

Revision ID: 0d14167fa1d1
Revises: 0734b1d10ef7
Create Date: 2021-04-08 02:23:56.857313

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d14167fa1d1'
down_revision = '0734b1d10ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsible_officer', 'email',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=True)
    op.alter_column('responsible_officer', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('responsible_officer', 'title',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('responsible_officer', 'title',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('responsible_officer', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('responsible_officer', 'email',
                    existing_type=mysql.VARCHAR(length=100),
                    nullable=False)
    # ### end Alembic commands ###
