"""empty message

Revision ID: 0d24df2a461b
Revises: c6a9b8765923
Create Date: 2020-09-14 21:32:48.518913

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d24df2a461b'
down_revision = 'c6a9b8765923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_rate', 'rate',
                    existing_type=mysql.DECIMAL(precision=6, scale=3),
                    type_=sa.String(length=10),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_rate', 'rate',
                    existing_type=sa.String(length=10),
                    type_=mysql.DECIMAL(precision=6, scale=3),
                    existing_nullable=False)
    # ### end Alembic commands ###
