"""empty message

Revision ID: 0e92543933a1
Revises: 1ecf8d6aefbb
Create Date: 2020-09-22 19:44:11.893349

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e92543933a1'
down_revision = '1ecf8d6aefbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED',
                                             'REJECTED', 'ASSIGNED', 'COMPLETED', 'BUDGETTED', 'ONGOING', 'SUSPENDED'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', name='projectstatus'),
                    existing_nullable=False)
    op.alter_column('project', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED',
                                             'REJECTED', 'ASSIGNED', 'COMPLETED', 'BUDGETTED', 'ONGOING', 'SUSPENDED'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', name='projectstatus'))
    op.alter_column('workflow', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED',
                                             'REJECTED', 'ASSIGNED', 'COMPLETED', 'BUDGETTED', 'ONGOING', 'SUSPENDED'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                  'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', name='projectstatus'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'project_status',
                    existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED',
                                          'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', name='projectstatus'),
                    type_=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                     'ASSIGNED', 'COMPLETED', 'BUDGETTED', 'ONGOING', 'SUSPENDED'),
                    existing_nullable=False)
    # ### end Alembic commands ###
