"""empty message

Revision ID: 111078cdc52a
Revises: 60949da7c702
Create Date: 2020-09-17 03:44:04.591002

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '111078cdc52a'
down_revision = '60949da7c702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'role_id', sa.Integer(), nullable=False))

    op.execute("UPDATE workflow SET role_id = 1")
    op.create_foreign_key("workflow_role_id_ibfk",
                          'workflow', 'role', ['role_id'], ['id'])
    op.drop_column('workflow', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'role', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint("workflow_role_id_ibfk", 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'role_id')
    # ### end Alembic commands ###
