"""empty message

Revision ID: 11c4429212ed
Revises: b44babb50aea
Create Date: 2021-06-14 18:30:07.883075

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11c4429212ed'
down_revision = 'b44babb50aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_public', sa.Boolean(),
                                       server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_public')
    # ### end Alembic commands ###
