"""empty message

Revision ID: 152dbbc4441d
Revises: 9510fe41c0a5
Create Date: 2021-10-22 00:10:36.138950

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '152dbbc4441d'
down_revision = '9510fe41c0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndp_sdg', sa.Column('ndp_outcome_ids',
                                       sa.String(length=255), nullable=False))
    op.drop_constraint('ndp_sdg_ibfk_1', 'ndp_sdg', type_='foreignkey')
    op.drop_column('ndp_sdg', 'ndp_outcome_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndp_sdg', sa.Column('ndp_outcome_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('ndp_sdg_ibfk_1', 'ndp_sdg',
                          'ndp_outcome', ['ndp_outcome_id'], ['id'])
    op.drop_column('ndp_sdg', 'ndp_outcome_ids')
    # ### end Alembic commands ###
