"""empty message

Revision ID: 16f9e452781b
Revises: 994985175b6d
Create Date: 2021-09-01 23:05:11.202071

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16f9e452781b'
down_revision = '994985175b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_location', 'location_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.create_foreign_key("project_location_id", 'project_location', 'location', [
                          'location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
