"""empty message

Revision ID: 18a2cc30f401
Revises: 4e92e80da8c2
Create Date: 2022-05-01 13:15:36.509354

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18a2cc30f401'
down_revision = '4e92e80da8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_completion', sa.Column(
        'actual_end_date', sa.Date(), nullable=True))
    op.add_column('project_completion', sa.Column(
        'actual_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_completion', 'actual_start_date')
    op.drop_column('project_completion', 'actual_end_date')
    # ### end Alembic commands ###
