"""empty message

Revision ID: 190a0a807a71
Revises: 0d14167fa1d1
Create Date: 2021-04-08 03:00:08.139246

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '190a0a807a71'
down_revision = '0d14167fa1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'reason',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=mysql.TEXT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'reason',
                    existing_type=mysql.TEXT(),
                    type_=mysql.VARCHAR(length=255))
    # ### end Alembic commands ###
