"""empty message

Revision ID: 1aa358138691
Revises: 667b5735bdc5
Create Date: 2021-01-21 02:51:45.403101

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aa358138691'
down_revision = '667b5735bdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund', sa.Column('is_donor', sa.Boolean(),
                                    server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund', 'is_donor')
    # ### end Alembic commands ###
