"""empty message

Revision ID: 1aff87f14050
Revises: bc7c0a332bc5
Create Date: 2021-07-14 18:04:08.859060

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aff87f14050'
down_revision = 'bc7c0a332bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE me_report SET issues = NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
