"""empty message

Revision ID: 1e5144393463
Revises: 9398f2fd79fb
Create Date: 2020-09-10 01:52:23.533074

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e5144393463'
down_revision = '9398f2fd79fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'phase_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_detail',
                          'phase', ['phase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_detail', type_='foreignkey')
    op.drop_column('project_detail', 'phase_id')
    # ### end Alembic commands ###
