"""empty message

Revision ID: 1e7848665239
Revises: 6a10b89c1624
Create Date: 2021-03-17 16:28:07.246863

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e7848665239'
down_revision = '6a10b89c1624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output', sa.Column(
        'ndp_strategy_id', sa.Integer(), nullable=True))
    op.create_foreign_key("output_ndp_strategy_idx", 'output', 'ndp_strategy', [
                          'ndp_strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('output_ndp_strategy_idx', 'output', type_='foreignkey')
    op.drop_column('output', 'ndp_strategy_id')
    # ### end Alembic commands ###
