"""empty message

Revision ID: 1ecf8d6aefbb
Revises: 813c8f629226
Create Date: 2020-09-21 23:02:26.105088

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ecf8d6aefbb'
down_revision = '813c8f629226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('project_status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED',
                                                                  'REJECTED', 'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', name='projectstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'project_status')
    # ### end Alembic commands ###
