"""empty message

Revision ID: 1f57ff5c1da2
Revises: a9736973425e
Create Date: 2021-05-18 23:33:11.640652

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f57ff5c1da2'
down_revision = 'a9736973425e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'geo_location', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'geo_location')
    # ### end Alembic commands ###
