"""empty message

Revision ID: 1faccb575e31
Revises: fb96610ccce9
Create Date: 2021-04-22 13:58:21.451307

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1faccb575e31'
down_revision = 'fb96610ccce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column(
        'additional_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'additional_data')
    # ### end Alembic commands ###
