"""empty message

Revision ID: 2053b02f8f4b
Revises: 21f759d7ba2c
Create Date: 2020-12-22 01:27:25.619126

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2053b02f8f4b'
down_revision = '21f759d7ba2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'in_ndp', sa.Boolean(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_focus_area', sa.String(length=50), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_intervention', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_name', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_page_no', sa.SmallInteger(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_plan_details', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_strategic_directives', sa.String(length=100), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'ndp_type')
    op.drop_column('project_detail', 'ndp_strategic_directives')
    op.drop_column('project_detail', 'ndp_plan_details')
    op.drop_column('project_detail', 'ndp_page_no')
    op.drop_column('project_detail', 'ndp_name')
    op.drop_column('project_detail', 'ndp_intervention')
    op.drop_column('project_detail', 'ndp_focus_area')
    op.drop_column('project_detail', 'in_ndp')
    # ### end Alembic commands ###
