"""empty message

Revision ID: 20725afe8db4
Revises: 6cd1964b32c7
Create Date: 2020-09-13 16:24:10.799541

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20725afe8db4'
down_revision = '6cd1964b32c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_cycle_ibfk', 'project', type_='foreignkey')
    op.drop_column('project', 'cycle_id')
    op.drop_constraint('timeline_ibfk_3', 'timeline', type_='foreignkey')
    op.drop_column('timeline', 'cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('cycle_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('timeline_ibfk_3', 'timeline',
                          'cycle', ['cycle_id'], ['id'])
    op.add_column('project', sa.Column('cycle_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('project_cycle_ibfk', 'project',
                          'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###
