"""empty message

Revision ID: 2171029cd7d6
Revises: e92b64911669
Create Date: 2020-08-27 23:51:40.424488

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2171029cd7d6'
down_revision = 'e92b64911669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('has_allowed_projects',
                                    sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('role', sa.Column('organization_level',
                                    sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'organization_level')
    op.drop_column('role', 'has_allowed_projects')
    # ### end Alembic commands ###
