"""empty message

Revision ID: 21f759d7ba2c
Revises: a456cd32f132
Create Date: 2020-09-22 23:31:41.653193

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21f759d7ba2c'
down_revision = 'a456cd32f132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'me_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_report', 'me_type')
    # ### end Alembic commands ###
