"""empty message

Revision ID: 27eeca26b9b6
Revises: 78554890ad6a
Create Date: 2021-01-21 03:35:42.821550

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27eeca26b9b6'
down_revision = '78554890ad6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column(
        'project_id', sa.Integer(), nullable=False))
    op.create_foreign_key("comment_project_id_idx",
                          'comment', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_project_id_idx', 'comment', type_='foreignkey')
    op.drop_column('comment', 'project_id')
    # ### end Alembic commands ###
