"""empty message

Revision ID: 2893776a399e
Revises: e2a637309d09
Create Date: 2021-06-29 23:28:25.795552

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2893776a399e'
down_revision = 'e2a637309d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_output', sa.Column('output_status', sa.Enum('ON_TRACK', 'COMPLETED', 'DELAYED', 'SATISFACTORY',
                                                                  'NOT_SATISFACTORY', 'MODERATELY_SATISFACTORY', 'NO_ASSESSMENT', name='meoutputstatus'), nullable=False))
    op.add_column('me_output', sa.Column(
        'risk_description', sa.Text(), nullable=True))
    op.add_column('me_output', sa.Column(
        'risk_response', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_output', 'risk_response')
    op.drop_column('me_output', 'risk_description')
    op.drop_column('me_output', 'output_status')
    # ### end Alembic commands ###
