"""empty message

Revision ID: 295f141799cf
Revises: 0cf1b024c3ba
Create Date: 2020-08-24 21:36:24.343354

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '295f141799cf'
down_revision = '0cf1b024c3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('key', mysql.VARCHAR(
        charset='utf8', collation='utf8_general_ci', length=100), nullable=False))
    # ### end Alembic commands ###
