"""empty message

Revision ID: 2a012fc9d059
Revises: 6747881f0248
Create Date: 2021-03-31 17:49:05.739138

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a012fc9d059'
down_revision = '6747881f0248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'budget_allocation', sa.JSON(), nullable=True))
    op.add_column('project', sa.Column(
        'budget_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'budget_code')
    op.drop_column('project', 'budget_allocation')
    # ### end Alembic commands ###
