"""empty message

Revision ID: 2b181d5f34f8
Revises: 6839b3b200a0
Create Date: 2021-08-16 23:26:01.753209

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b181d5f34f8'
down_revision = '6839b3b200a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column(
        'management_id', sa.Integer(), nullable=True))
    op.create_foreign_key('organization_management_idx', 'organization', 'management', [
                          'management_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_management_idx',
                       'organization', type_='foreignkey')
    op.drop_column('organization', 'management_id')
    # ### end Alembic commands ###
