"""empty message

Revision ID: 2c0b078a3b82
Revises: 152dbbc4441d
Create Date: 2021-11-16 19:11:29.085713

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c0b078a3b82'
down_revision = '152dbbc4441d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costing', sa.Column('is_om_applicable',
                                       sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costing', 'is_om_applicable')
    # ### end Alembic commands ###
