"""empty message

Revision ID: 33b361a32a21
Revises: 89ded3eac34f
Create Date: 2020-09-19 23:30:26.508152

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33b361a32a21'
down_revision = '89ded3eac34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output', sa.Column(
        'alternative_specs', sa.Text(), nullable=True))
    op.add_column('output', sa.Column('tech_specs', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'me_strategies', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'sustainability_plan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'sustainability_plan')
    op.drop_column('project_detail', 'me_strategies')
    op.drop_column('output', 'tech_specs')
    op.drop_column('output', 'alternative_specs')
    # ### end Alembic commands ###
