"""empty message

Revision ID: 3aad23c67a53
Revises: a867b81b2cdd
Create Date: 2021-08-10 18:07:40.307768

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aad23c67a53'
down_revision = 'a867b81b2cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'financing_agreement_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_report', 'financing_agreement_date')
    # ### end Alembic commands ###
