"""empty message

Revision ID: 3c63b0d20aed
Revises: 7d17d7e2ae37
Create Date: 2021-03-02 00:10:02.659569

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c63b0d20aed'
down_revision = '7d17d7e2ae37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakeholder_evaluation', sa.Column(
        'communication_channel', sa.Text(), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'engagement_frequency', sa.String(length=20), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'influence_level', sa.String(length=10), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'interest_level', sa.String(length=10), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'responsible_entity', sa.String(length=255), nullable=True))
    op.alter_column('stakeholder_evaluation', 'beneficiary',
                    existing_type=mysql.VARCHAR(length=10),
                    nullable=True)
    op.alter_column('stakeholder_evaluation', 'impact_sign',
                    existing_type=mysql.VARCHAR(length=10),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stakeholder_evaluation', 'impact_sign',
                    existing_type=mysql.VARCHAR(length=10),
                    nullable=False)
    op.alter_column('stakeholder_evaluation', 'beneficiary',
                    existing_type=mysql.VARCHAR(length=10),
                    nullable=False)
    op.drop_column('stakeholder_evaluation', 'responsible_entity')
    op.drop_column('stakeholder_evaluation', 'interest_level')
    op.drop_column('stakeholder_evaluation', 'influence_level')
    op.drop_column('stakeholder_evaluation', 'engagement_frequency')
    op.drop_column('stakeholder_evaluation', 'communication_channel')
    # ### end Alembic commands ###
