"""empty message

Revision ID: 3d8e6a083a81
Revises: 3aad23c67a53
Create Date: 2021-08-12 16:08:22.319126

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d8e6a083a81'
down_revision = '3aad23c67a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_activity', 'fund_source',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_activity', 'fund_source',
                    existing_type=mysql.VARCHAR(length=30),
                    nullable=False)
    # ### end Alembic commands ###
