"""empty message

Revision ID: 3ec6eef724cd
Revises: 87e138a59d98
Create Date: 2021-01-12 22:50:48.017257

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ec6eef724cd'
down_revision = '87e138a59d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'supervisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['supervisor_id'], ['id'])
    op.create_foreign_key(None, 'user', 'fund', ['fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'supervisor_id')
    # ### end Alembic commands ###
