"""empty message

Revision ID: 427c84662b03
Revises: b218ed37b3d9
Create Date: 2021-12-08 09:22:19.045588

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '427c84662b03'
down_revision = 'b218ed37b3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column(
        'component_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'component_ids')
    # ### end Alembic commands ###
