"""empty message

Revision ID: 435e8a151cbf
Revises: 5f4e27a975d5
Create Date: 2021-01-14 02:55:41.773187

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '435e8a151cbf'
down_revision = '5f4e27a975d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column(
        'approved_by', sa.Integer(), nullable=True))
    op.add_column('user_role', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('user_role', sa.Column('is_approved', sa.Boolean(),
                                         server_default=sa.text('false'), nullable=False))
    op.add_column('user_role', sa.Column(
        'start_date', sa.Date(), nullable=True))
    op.create_foreign_key("user_role_approved_idx",
                          'user_role', 'user', ['approved_by'], ['id'])
    op.execute("UPDATE user_role SET is_approved = 1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_role_approved_idx",
                       'user_role', type_='foreignkey')
    op.drop_column('user_role', 'start_date')
    op.drop_column('user_role', 'is_approved')
    op.drop_column('user_role', 'end_date')
    op.drop_column('user_role', 'approved_by')
    # ### end Alembic commands ###
