"""empty message

Revision ID: 44def51cf11f
Revises: 6baab65e0ba5
Create Date: 2020-09-14 22:33:14.471513

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44def51cf11f'
down_revision = '6baab65e0ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investment_ibfk_1', 'investment', type_='foreignkey')
    op.create_foreign_key('investment_ibfk_1', 'investment',
                          'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investment_ibfk_1', 'investment', type_='foreignkey')
    op.create_foreign_key('investment_ibfk_1', 'investment', 'activity', [
                          'activity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
