"""empty message

Revision ID: 465f6eb72599
Revises: 427c84662b03
Create Date: 2021-12-13 00:01:21.026846

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '465f6eb72599'
down_revision = '427c84662b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column(
        'description', sa.Text(), nullable=True))
    op.drop_column('outcome', 'component_ids')
    op.add_column('output', sa.Column(
        'component_ids', sa.JSON(), nullable=True))
    op.alter_column('output', 'unit_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.add_column('project_detail', sa.Column(
        'goal_description', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'project_goal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'project_goal')
    op.drop_column('project_detail', 'goal_description')
    op.alter_column('output', 'unit_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.drop_column('output', 'component_ids')
    op.add_column('outcome', sa.Column(
        'component_ids', mysql.JSON(), nullable=True))
    op.drop_column('outcome', 'description')
    # ### end Alembic commands ###
