"""empty message

Revision ID: 493577d9455f
Revises: 01d003783a38
Create Date: 2021-04-07 23:16:24.940228

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '493577d9455f'
down_revision = '01d003783a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('government_coordination', 'organization_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.drop_constraint('government_coordination_ibfk_1',
                       'government_coordination', type_='foreignkey')
    op.create_foreign_key('government_coordination_org_id_key',
                          'government_coordination', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('government_coordination_org_id_key',
                       'government_coordination', type_='foreignkey')
    op.create_foreign_key('government_coordination_ibfk_1',
                          'government_coordination', 'organization2', ['organization_id'], ['id'])
    op.alter_column('government_coordination', 'organization_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    # ### end Alembic commands ###
