"""empty message

Revision ID: 4aa2557b00ed
Revises: 16f9e452781b
Create Date: 2021-09-10 03:05:32.056467

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aa2557b00ed'
down_revision = '16f9e452781b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'management_id', sa.Integer(), nullable=True))
    op.create_foreign_key('user_management_id', 'user',
                          'management', ['management_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_management_id', 'user', type_='foreignkey')
    op.drop_column('user', 'management_id')
    # ### end Alembic commands ###
