"""empty message

Revision ID: 4c6c54841ef8
Revises: bbcfd58bb8ff
Create Date: 2021-10-06 01:57:32.378149

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c6c54841ef8'
down_revision = 'bbcfd58bb8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'ranking_data', sa.JSON(), nullable=True))
    op.add_column('project', sa.Column(
        'ranking_score', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'ranking_score')
    op.drop_column('project', 'ranking_data')
    # ### end Alembic commands ###
