"""empty message

Revision ID: 4e92e80da8c2
Revises: 465f6eb72599
Create Date: 2022-02-08 00:34:12.242146

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e92e80da8c2'
down_revision = '465f6eb72599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_framework_updated',
                                       sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_framework_updated')
    # ### end Alembic commands ###
