"""empty message

Revision ID: 4f31826d3dfd
Revises: 67a4ee9660f5
Create Date: 2021-08-20 04:59:55.318917

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f31826d3dfd'
down_revision = '67a4ee9660f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'is_resilient', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'is_resilient')
    # ### end Alembic commands ###
