"""empty message

Revision ID: 56561aac764a
Revises: 33b361a32a21
Create Date: 2020-09-19 23:38:14.284663

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56561aac764a'
down_revision = '33b361a32a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'evaluation_period', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'evaluation_period')
    # ### end Alembic commands ###
