"""empty message

Revision ID: 5916d0b393f7
Revises: 6ae40f9d1dc5
Create Date: 2021-03-14 03:20:13.240448

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5916d0b393f7'
down_revision = '6ae40f9d1dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'additional_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'additional_data')
    # ### end Alembic commands ###
