"""empty message

Revision ID: 5b1382673aea
Revises: 6de785bf5db0
Create Date: 2020-09-16 14:03:33.247570

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b1382673aea'
down_revision = '6de785bf5db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_ibfk_1', 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'assigned_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('assigned_user_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('workflow_ibfk_1', 'workflow',
                          'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###
