"""empty message

Revision ID: 5c87c68bde5d
Revises: 73ab047f04ad
Create Date: 2021-06-24 11:48:58.619932

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c87c68bde5d'
down_revision = '73ab047f04ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_report', 'disbursement',
                    existing_type=mysql.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_report', 'disbursement',
                    existing_type=mysql.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
