"""empty message

Revision ID: 5ce68c76aeb7
Revises: eb0b0fc49743
Create Date: 2020-09-17 19:36:16.680153

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ce68c76aeb7'
down_revision = 'eb0b0fc49743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column(
        'current_step', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE timeline SET current_step = 1")
    op.alter_column('timeline', 'current_step',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    op.add_column('project', sa.Column(
        'max_step', sa.SmallInteger(), nullable=True))
    op.execute("UPDATE project SET max_step = 1")
    op.alter_column('project', 'max_step',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'max_step')
    op.drop_column('timeline', 'current_step')
    # ### end Alembic commands ###
