"""empty message

Revision ID: 5d1b2da8e987
Revises: 3c63b0d20aed
Create Date: 2021-03-02 00:31:53.845366

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d1b2da8e987'
down_revision = '3c63b0d20aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_option', sa.Column(
        'contract_management', sa.Text(), nullable=True))
    op.add_column('project_option', sa.Column(
        'me_strategy', sa.Text(), nullable=True))
    op.add_column('project_option', sa.Column(
        'risk_allocation', sa.Text(), nullable=True))
    op.add_column('project_option', sa.Column(
        'value_for_money', sa.Text(), nullable=True))
    op.alter_column('project_option', 'funding_modality',
                    existing_type=mysql.ENUM('PARTNERSHIP', 'PROCUREMENT'),
                    type_=sa.Enum('PARTNERSHIP', 'PROCUREMENT', 'JOINT_VENTURE',
                                  'UNSOLICITED_PROPOSAL', name='fundingmodality'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'funding_modality',
                    existing_type=sa.Enum(
                        'PARTNERSHIP', 'PROCUREMENT', 'JOINT_VENTURE', 'UNSOLICITED_PROPOSAL', name='fundingmodality'),
                    type_=mysql.ENUM('PARTNERSHIP', 'PROCUREMENT'),
                    existing_nullable=True)
    op.drop_column('project_option', 'value_for_money')
    op.drop_column('project_option', 'risk_allocation')
    op.drop_column('project_option', 'me_strategy')
    op.drop_column('project_option', 'contract_management')
    # ### end Alembic commands ###
