"""empty message

Revision ID: 5e22145d5e33
Revises: 923a84f9d74e
Create Date: 2021-03-01 05:08:51.980659

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e22145d5e33'
down_revision = '923a84f9d74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'cost',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'cost',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    # ### end Alembic commands ###
