"""empty message

Revision ID: 5f4e27a975d5
Revises: 3ec6eef724cd
Create Date: 2021-01-13 01:17:16.180972

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f4e27a975d5'
down_revision = '3ec6eef724cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key("project_assigned_user_idx",
                          'project', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_assigned_user_idx",
                       'project', type_='foreignkey')
    op.drop_column('project', 'assigned_user_id')
    # ### end Alembic commands ###
