"""empty message

Revision ID: 60949da7c702
Revises: 03fe98e02a5c
Create Date: 2020-09-17 03:21:15.666437

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60949da7c702'
down_revision = '03fe98e02a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflow_ibfk_2', 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'cycle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('cycle_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('workflow_ibfk_2', 'workflow',
                          'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###
