"""empty message

Revision ID: 61db862537e9
Revises: 1e5144393463
Create Date: 2020-09-10 22:30:20.886514

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61db862537e9'
down_revision = '1e5144393463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'additional_data', sa.JSON(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'end_date', sa.DateTime(), nullable=False))
    op.add_column('project_detail', sa.Column(
        'exec_management_plan', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'liability_period', sa.SmallInteger(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'maintenance_period', sa.SmallInteger(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'methodology', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'organization_study', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'other_info', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'rational_study', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'start_date', sa.DateTime(), nullable=False))
    op.add_column('project_detail', sa.Column(
        'summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'summary')
    op.drop_column('project_detail', 'start_date')
    op.drop_column('project_detail', 'rational_study')
    op.drop_column('project_detail', 'other_info')
    op.drop_column('project_detail', 'organization_study')
    op.drop_column('project_detail', 'methodology')
    op.drop_column('project_detail', 'maintenance_period')
    op.drop_column('project_detail', 'liability_period')
    op.drop_column('project_detail', 'exec_management_plan')
    op.drop_column('project_detail', 'end_date')
    op.drop_column('project_detail', 'additional_data')
    # ### end Alembic commands ###
