"""empty message

Revision ID: 64d4b130bd12
Revises: 82b4a9ad389a
Create Date: 2021-04-12 00:01:53.086539

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64d4b130bd12'
down_revision = '82b4a9ad389a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column(
        'organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key("function_org_id_idx", 'function',
                          'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('function_org_id_idx', 'function', type_='foreignkey')
    op.drop_column('function', 'organization_id')
    # ### end Alembic commands ###
