"""empty message

Revision ID: 667b5735bdc5
Revises: b032c815191c
Create Date: 2021-01-21 02:01:54.295226

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '667b5735bdc5'
down_revision = 'b032c815191c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'fund_ids', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'fund_ids')
    # ### end Alembic commands ###
