"""empty message

Revision ID: 6747881f0248
Revises: 9e1d6b398dd0
Create Date: 2021-03-28 02:20:28.589014

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6747881f0248'
down_revision = '9e1d6b398dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'budget_allocation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'budget_allocation')
    # ### end Alembic commands ###
