"""empty message

Revision ID: 67a4ee9660f5
Revises: 2b181d5f34f8
Create Date: 2021-08-20 04:10:42.567323

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67a4ee9660f5'
down_revision = '2b181d5f34f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_location', sa.Column(
        'administrative_post', sa.String(length=255), nullable=True))
    op.add_column('project_location', sa.Column(
        'country_name', sa.String(length=255), nullable=True))
    op.add_column('project_location', sa.Column(
        'location_name', sa.String(length=255), nullable=True))
    op.add_column('project_location', sa.Column(
        'location_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_location', 'location_type')
    op.drop_column('project_location', 'location_name')
    op.drop_column('project_location', 'country_name')
    op.drop_column('project_location', 'administrative_post')
    # ### end Alembic commands ###
