"""empty message

Revision ID: 6839b3b200a0
Revises: 11c4429212ed
Create Date: 2021-08-04 17:26:21.068140

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6839b3b200a0'
down_revision = '11c4429212ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'proposed_funding_source', sa.JSON(), nullable=True))
    op.alter_column('project_detail', 'revenue_source',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.execute(
        'update project_detail set revenue_source=CONCAT(\'["\', revenue_source, \'"]\')')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_detail', 'revenue_source',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    op.drop_column('project_detail', 'proposed_funding_source')
    # ### end Alembic commands ###
