"""empty message

Revision ID: 699f339d1e28
Revises: 20725afe8db4
Create Date: 2020-09-13 19:12:33.765016

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '699f339d1e28'
down_revision = '20725afe8db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("timeline_created_user_ibfk",
                          'timeline', 'user', ['created_by'], ['id'])
    op.add_column('user', sa.Column(
        'last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_time')
    op.drop_constraint('timeline_created_user_ibfk',
                       'timeline', type_='foreignkey')
    # ### end Alembic commands ###
