"""empty message

Revision ID: 6a10b89c1624
Revises: 5916d0b393f7
Create Date: 2021-03-17 01:18:09.226470

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a10b89c1624'
down_revision = '5916d0b393f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('program_name_unq', table_name='program')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('program_name_unq', 'program', ['name'], unique=True)
    # ### end Alembic commands ###
