"""empty message

Revision ID: 6a9ea7f6c2ca
Revises: abf1b61d9cfe
Create Date: 2021-03-01 02:54:36.701360

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9ea7f6c2ca'
down_revision = 'abf1b61d9cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_detail', 'ndp_strategies',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_detail', 'ndp_strategies',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
