"""empty message

Revision ID: 6ae40f9d1dc5
Revises: bf761d716de6
Create Date: 2021-03-14 02:52:35.912516

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ae40f9d1dc5'
down_revision = 'bf761d716de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column(
        'assigned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('timeline_assigned_user_idx',
                          'timeline', 'user', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timeline_assigned_user_idx',
                       'timeline', type_='foreignkey')
    op.drop_column('timeline', 'assigned_user_id')
    # ### end Alembic commands ###
