"""empty message

Revision ID: 6cd1964b32c7
Revises: a64c63ef4f22
Create Date: 2020-09-13 15:14:27.235699

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cd1964b32c7'
down_revision = 'a64c63ef4f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'cycle_id', sa.Integer(), nullable=False))
    op.execute("UPDATE project SET cycle_id = 1")
    op.create_foreign_key("project_cycle_ibfk", 'project',
                          'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_cycle_ibfk", 'project', type_='foreignkey')
    op.drop_column('project', 'cycle_id')
    # ### end Alembic commands ###
