"""empty message

Revision ID: 6de785bf5db0
Revises: c5514de47925
Create Date: 2020-09-16 13:49:44.343050

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6de785bf5db0'
down_revision = 'c5514de47925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'problem_effects', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'stakeholders', sa.Text(), nullable=True))
    op.drop_column('project_detail', 'problem_effect')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'problem_effect', mysql.TEXT(), nullable=True))
    op.drop_column('project_detail', 'stakeholders')
    op.drop_column('project_detail', 'problem_effects')
    # ### end Alembic commands ###
