"""empty message

Revision ID: 6e232de36c86
Revises: 5b1382673aea
Create Date: 2020-09-16 19:39:56.743702

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e232de36c86'
down_revision = '5b1382673aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'om_cost', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'om_cost')
    # ### end Alembic commands ###
