"""empty message

Revision ID: 73ab047f04ad
Revises: e7d40e4b5a5d
Create Date: 2021-06-24 10:54:36.209961

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73ab047f04ad'
down_revision = 'e7d40e4b5a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_report', 'report_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'ASSIGNED',
                                  'COMPLETED', name='reportstatus'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_report', 'report_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'ASSIGNED',
                                             'COMPLETED'),
                    type_=sa.Enum('DRAFT', 'SUBMITTED'),
                    existing_nullable=False)
    # ### end Alembic commands ###
