"""empty message

Revision ID: 73f29ae9744d
Revises: 95e83805b256
Create Date: 2020-09-14 00:39:51.263724

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73f29ae9744d'
down_revision = '95e83805b256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'password_changed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_changed_on')
    # ### end Alembic commands ###
