"""empty message

Revision ID: 77fa8923fea8
Revises: 73f29ae9744d
Create Date: 2020-09-14 02:06:04.903770

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77fa8923fea8'
down_revision = '73f29ae9744d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'baseline', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'baseline')
    # ### end Alembic commands ###
