"""empty message

Revision ID: 78554890ad6a
Revises: 1aa358138691
Create Date: 2021-01-21 02:55:13.793706

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78554890ad6a'
down_revision = '1aa358138691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_donor_funded', sa.Boolean(),
                                       server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_donor_funded')
    # ### end Alembic commands ###
