"""empty message

Revision ID: 7d17d7e2ae37
Revises: 5e22145d5e33
Create Date: 2021-03-01 05:25:29.365846

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d17d7e2ae37'
down_revision = '5e22145d5e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'capital_expenditure',
                    existing_type=mysql.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.alter_column('project_option', 'om_cost',
                    existing_type=mysql.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'om_cost',
                    existing_type=sa.JSON(),
                    type_=mysql.TEXT(),
                    existing_nullable=True)
    op.alter_column('project_option', 'capital_expenditure',
                    existing_type=sa.JSON(),
                    type_=mysql.TEXT(),
                    existing_nullable=True)
    # ### end Alembic commands ###
