"""empty message

Revision ID: 7dabfa08d067
Revises: 27eeca26b9b6
Create Date: 2021-01-22 00:36:48.423651

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dabfa08d067'
down_revision = '27eeca26b9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'start_date', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column(
        'end_date', sa.DateTime(), nullable=True))
    op.execute("""UPDATE project
                INNER JOIN project_detail ON project.id = project_detail.project_id
                SET project.start_date = project_detail.start_date,
                project.end_date=project_detail.end_date""")
    op.alter_column('project', 'start_date',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.alter_column('project', 'end_date',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'end_date')
    # ### end Alembic commands ###
