"""empty message

Revision ID: 7ea82d470101
Revises: ecf737574579
Create Date: 2022-05-04 18:31:53.503575

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ea82d470101'
down_revision = 'ecf737574579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('ndp_pip_code',
                                       sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'ndp_pip_code')
    # ### end Alembic commands ###
