"""empty message

Revision ID: 7efc17ba1cdd
Revises: 6e232de36c86
Create Date: 2020-09-16 20:35:40.532261

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7efc17ba1cdd'
down_revision = '6e232de36c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'om_costing_id', sa.Integer(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'om_fund_id', sa.Integer(), nullable=True))
    op.create_foreign_key("project_detail_costing_ibfk",
                          'project_detail', 'costing', ['om_costing_id'], ['id'])
    op.create_foreign_key("project_detail_fund_ibfk",
                          'project_detail', 'fund', ['om_fund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_detail_fund_ibfk",
                       'project_detail', type_='foreignkey')
    op.drop_constraint("project_detail_costing_ibfk",
                       'project_detail', type_='foreignkey')
    op.drop_column('project_detail', 'om_fund_id')
    op.drop_column('project_detail', 'om_costing_id')
    # ### end Alembic commands ###
