"""empty message

Revision ID: 7f1e46dec803
Revises: 3d8e6a083a81
Create Date: 2021-08-20 04:14:52.721313

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f1e46dec803'
down_revision = '3d8e6a083a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'signed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'signed_date')
    # ### end Alembic commands ###
