"""empty message

Revision ID: 82b4a9ad389a
Revises: 84c8d49a07ce
Create Date: 2021-04-11 23:56:37.474533

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82b4a9ad389a'
down_revision = '84c8d49a07ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('organization_ids',
                                       sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'organization_ids')
    # ### end Alembic commands ###
