"""empty message

Revision ID: 83032d1ab6a8
Revises: aff2b0eabc8c
Create Date: 2020-08-13 16:55:54.918963

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83032d1ab6a8'
down_revision = 'aff2b0eabc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'roles', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###
