"""empty message

Revision ID: 84c8d49a07ce
Revises: 190a0a807a71
Create Date: 2021-04-08 03:13:06.118505

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84c8d49a07ce'
down_revision = '190a0a807a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.String(length=50),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
                    existing_type=sa.String(length=50),
                    type_=mysql.VARCHAR(length=20),
                    existing_nullable=False)
    # ### end Alembic commands ###
