"""empty message

Revision ID: 85f40c04742b
Revises: c6c7e56fe844
Create Date: 2021-03-13 02:25:41.887479

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f40c04742b'
down_revision = 'c6c7e56fe844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'function_id', sa.Integer(), nullable=True))
    op.create_foreign_key('project_function_id_idx',
                          'project', 'function', ['function_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_function_id_idx',
                       'project', type_='foreignkey')
    op.drop_column('project', 'function_id')
    # ### end Alembic commands ###
