"""empty message

Revision ID: 87e138a59d98
Revises: cf92ecf3d2b9
Create Date: 2021-01-12 16:29:31.054133

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87e138a59d98'
down_revision = 'cf92ecf3d2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('fund_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(),
                                    server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column(
        'phone', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'is_blocked')
    op.drop_column('user', 'fund_id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
