"""empty message

Revision ID: 89ded3eac34f
Revises: cc59d5847814
Create Date: 2020-09-19 22:28:34.142908

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ded3eac34f'
down_revision = 'cc59d5847814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'stakeholders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'stakeholders', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
