"""empty message

Revision ID: 8a6232bd68a5
Revises: b2d4f33ca29b
Create Date: 2021-03-18 00:35:57.799156

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a6232bd68a5'
down_revision = 'b2d4f33ca29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'issues', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('project_detail', 'recommendations')
    op.drop_column('project_detail', 'issues')
    # ### end Alembic commands ###
