"""empty message

Revision ID: 8ab32a9925af
Revises: 9c539b7e9fa0
Create Date: 2020-09-15 16:41:11.858839

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ab32a9925af'
down_revision = '9c539b7e9fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('investment_ibfk_5', 'investment', type_='foreignkey')
    op.drop_column('investment', 'currency_rate_id')
    op.add_column('project_detail', sa.Column(
        'currency_rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key("project_detail_currency_rate_ibfk",
                          'project_detail', 'currency_rate', ['currency_rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_detail_currency_rate_ibfk",
                       'project_detail', type_='foreignkey')
    op.drop_column('project_detail', 'currency_rate_id')
    op.add_column('investment', sa.Column('currency_rate_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('investment_ibfk_5', 'investment',
                          'currency_rate', ['currency_rate_id'], ['id'])
    # ### end Alembic commands ###
