"""empty message

Revision ID: 923a84f9d74e
Revises: ca0ccae4a887
Create Date: 2021-03-01 04:55:13.275854

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '923a84f9d74e'
down_revision = 'ca0ccae4a887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_option', sa.Column(
        'capital_expenditure', sa.Text(), nullable=True))
    op.add_column('project_option', sa.Column(
        'end_date', sa.Date(), nullable=True))
    op.add_column('project_option', sa.Column(
        'om_cost', sa.Text(), nullable=True))
    op.add_column('project_option', sa.Column(
        'om_end_date', sa.Date(), nullable=True))
    op.add_column('project_option', sa.Column(
        'om_start_date', sa.Date(), nullable=True))
    op.add_column('project_option', sa.Column(
        'start_date', sa.Date(), nullable=True))
    op.add_column('project_option', sa.Column(
        'swot_analysis', sa.Text(), nullable=True))
    op.alter_column('project_option', 'funding_modality',
                    existing_type=mysql.ENUM('PARTNERSHIP', 'PROCUREMENT'),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'funding_modality',
                    existing_type=mysql.ENUM('PARTNERSHIP', 'PROCUREMENT'),
                    nullable=False)
    op.drop_column('project_option', 'swot_analysis')
    op.drop_column('project_option', 'start_date')
    op.drop_column('project_option', 'om_start_date')
    op.drop_column('project_option', 'om_end_date')
    op.drop_column('project_option', 'om_cost')
    op.drop_column('project_option', 'end_date')
    op.drop_column('project_option', 'capital_expenditure')
    # ### end Alembic commands ###
