"""empty message

Revision ID: 9398f2fd79fb
Revises: 2171029cd7d6
Create Date: 2020-09-08 15:30:31.054838

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9398f2fd79fb'
down_revision = '2171029cd7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'allowed_organization_ids',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=sa.JSON(),
                    existing_nullable=True)
    op.alter_column('user_role', 'allowed_project_ids',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_role', 'allowed_project_ids',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    op.alter_column('user_role', 'allowed_organization_ids',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
