"""empty message

Revision ID: 9510fe41c0a5
Revises: b6731a70f3a5
Create Date: 2021-10-21 22:57:52.102715

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9510fe41c0a5'
down_revision = 'b6731a70f3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'update project_detail set procurement_modality=NULL where procurement_modality=""')
    op.execute(
        'update project_detail set procurement_modality=CONCAT(\'["\', procurement_modality, \'"]\')')
    op.alter_column('project_detail', 'procurement_modality',
                    existing_type=mysql.VARCHAR(length=255),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_detail', 'procurement_modality',
                    existing_type=sa.JSON(),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
