"""empty message

Revision ID: 95e83805b256
Revises: 699f339d1e28
Create Date: 2020-09-13 21:34:56.867032

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95e83805b256'
down_revision = '699f339d1e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'goal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'goal')
    # ### end Alembic commands ###
