"""empty message

Revision ID: 963ee01b5678
Revises: 435e8a151cbf
Create Date: 2021-01-16 23:13:25.543537

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '963ee01b5678'
down_revision = '435e8a151cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('is_delegated', sa.Boolean(),
                                         server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'is_delegated')
    # ### end Alembic commands ###
