"""empty message

Revision ID: 987ad3723b52
Revises: ad83492d097f
Create Date: 2020-08-17 21:08:32.737368

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '987ad3723b52'
down_revision = 'ad83492d097f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costing', sa.Column(
        'additional_data', sa.JSON(), nullable=True))
    op.add_column('fund', sa.Column(
        'additional_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund', 'additional_data')
    op.drop_column('costing', 'additional_data')
    # ### end Alembic commands ###
