"""empty message

Revision ID: 994985175b6d
Revises: 4f31826d3dfd
Create Date: 2021-08-29 22:52:54.252692

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '994985175b6d'
down_revision = '4f31826d3dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_type',
                                       sa.String(length=50), nullable=True))
    op.add_column('project_detail', sa.Column(
        'pillar_id', sa.Integer(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'resilience', sa.Text(), nullable=True))
    op.create_foreign_key('project_detail_pillar_id',
                          'project_detail', 'pillar', ['pillar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_detail_pillar_id',
                       'project_detail', type_='foreignkey')
    op.drop_column('project_detail', 'resilience')
    op.drop_column('project_detail', 'pillar_id')
    op.drop_column('project', 'project_type')
    # ### end Alembic commands ###
