"""empty message

Revision ID: 99975ec08b29
Revises: 2053b02f8f4b
Create Date: 2020-12-27 01:03:37.418661

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99975ec08b29'
down_revision = '2053b02f8f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'meta',
                    existing_type=mysql.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'meta',
                    existing_type=sa.JSON(),
                    type_=mysql.TEXT(),
                    existing_nullable=True)
    # ### end Alembic commands ###
