"""empty message

Revision ID: 9a760150eecd
Revises: 111078cdc52a
Create Date: 2020-09-17 03:55:20.187097

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a760150eecd'
down_revision = '111078cdc52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'revise_to_workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key("workflow_revise_ibfk", 'workflow', 'workflow', [
                          'revise_to_workflow_id'], ['id'])
    op.drop_column('workflow', 'revise_to_step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('revise_to_step', mysql.SMALLINT(
        display_width=6), autoincrement=False, nullable=True))
    op.drop_constraint("workflow_revise_ibfk", 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'revise_to_workflow_id')
    # ### end Alembic commands ###
