"""empty message

Revision ID: 9b712207656e
Revises: 5d1b2da8e987
Create Date: 2021-03-03 00:49:40.462852

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b712207656e'
down_revision = '5d1b2da8e987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'stakeholder_consultation', sa.Text(), nullable=True))
    op.add_column('stakeholder', sa.Column(
        'communication_channel', sa.Text(), nullable=True))
    op.add_column('stakeholder', sa.Column(
        'engagement_frequency', sa.String(length=20), nullable=True))
    op.add_column('stakeholder', sa.Column(
        'influence_level', sa.String(length=10), nullable=True))
    op.add_column('stakeholder', sa.Column(
        'interest_level', sa.String(length=10), nullable=True))
    op.add_column('stakeholder', sa.Column(
        'responsible_entity', sa.String(length=255), nullable=True))
    op.drop_column('stakeholder_evaluation', 'responsible_entity')
    op.drop_column('stakeholder_evaluation', 'influence_level')
    op.drop_column('stakeholder_evaluation', 'interest_level')
    op.drop_column('stakeholder_evaluation', 'communication_channel')
    op.drop_column('stakeholder_evaluation', 'engagement_frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stakeholder_evaluation', sa.Column(
        'engagement_frequency', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'communication_channel', mysql.TEXT(), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'interest_level', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'influence_level', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('stakeholder_evaluation', sa.Column(
        'responsible_entity', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('stakeholder', 'responsible_entity')
    op.drop_column('stakeholder', 'interest_level')
    op.drop_column('stakeholder', 'influence_level')
    op.drop_column('stakeholder', 'engagement_frequency')
    op.drop_column('stakeholder', 'communication_channel')
    op.drop_column('project_detail', 'stakeholder_consultation')
    # ### end Alembic commands ###
