"""empty message

Revision ID: 9c539b7e9fa0
Revises: 44def51cf11f
Create Date: 2020-09-15 16:35:14.358020

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c539b7e9fa0'
down_revision = '44def51cf11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('targets', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator', 'targets')
    # ### end Alembic commands ###
