"""empty message

Revision ID: 9e1d6b398dd0
Revises: 8a6232bd68a5
Create Date: 2021-03-24 00:09:27.090986

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e1d6b398dd0'
down_revision = '8a6232bd68a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE `timeline` CHANGE `project_action` `project_action` ENUM('CREATE','SUBMIT','APPROVE','REVISE','REJECT','ASSIGN','COMPLETE','ALLOCATE_FUNDS','SUSPEND', 'REVERT') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
