"""empty message

Revision ID: 9fcf492158e8
Revises: cff402fb7950
Create Date: 2020-08-22 21:48:39.251393

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fcf492158e8'
down_revision = 'cff402fb7950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workflow', ['step'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='unique')
    # ### end Alembic commands ###
