"""empty message

Revision ID: a456cd32f132
Revises: 0e92543933a1
Create Date: 2020-09-22 21:17:23.956895

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a456cd32f132'
down_revision = '0e92543933a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'),
                    nullable=False)
    op.alter_column('workflow', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED', 'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION', 'IN_PIPELINE'))
    op.alter_column('timeline', 'project_action',
                    existing_type=mysql.ENUM(
                        'CREATE', 'SUBMIT', 'APPROVE', 'REVISE', 'REJECT', 'ASSIGN', 'COMPLETE', 'SUSPEND'),
                    type_=sa.Enum('CREATE', 'SUBMIT', 'APPROVE', 'REVISE', 'REJECT', 'ASSIGN',
                                  'COMPLETE', 'ALLOCATE_FUNDS', 'SUSPEND', name='projectaction'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'project_action',
                    existing_type=sa.Enum('CREATE', 'SUBMIT', 'APPROVE', 'REVISE', 'REJECT',
                                          'ASSIGN', 'COMPLETE', 'ALLOCATE_FUNDS', 'SUSPEND', name='projectaction'),
                    type_=mysql.ENUM('CREATE', 'SUBMIT', 'APPROVE', 'REVISE',
                                     'REJECT', 'ASSIGN', 'COMPLETE', 'SUSPEND'),
                    existing_nullable=False)
    op.alter_column('project', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION'),
                    nullable=True)
    op.alter_column('workflow', 'project_status',
                    existing_type=mysql.ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REVISED', 'REJECTED',
                                             'ASSIGNED', 'COMPLETED', 'ONGOING', 'SUSPENDED', 'POST_EVALUATION'))
    # ### end Alembic commands ###
