"""empty message

Revision ID: a64c63ef4f22
Revises: 61db862537e9
Create Date: 2020-09-12 21:38:38.791944

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a64c63ef4f22'
down_revision = '61db862537e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'last_detail_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('last_detail_id', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
