"""empty message

Revision ID: a867b81b2cdd
Revises: 1aff87f14050
Create Date: 2021-07-21 14:13:51.356395

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a867b81b2cdd'
down_revision = '1aff87f14050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_activity', 'budget_allocation',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('me_activity', 'budget_appropriation',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('me_activity', 'financial_execution',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_activity', 'financial_execution',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    op.alter_column('me_activity', 'budget_appropriation',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    op.alter_column('me_activity', 'budget_allocation',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    # ### end Alembic commands ###
