"""empty message

Revision ID: a9736973425e
Revises: eb5f596917eb
Create Date: 2021-05-05 00:06:33.227268

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9736973425e'
down_revision = 'eb5f596917eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climate_risk', sa.Column(
        'climate_hazard_other', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'default_option_description_impact', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'revenue_source_other', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'revenue_source_other')
    op.drop_column('project_detail', 'default_option_description_impact')
    op.drop_column('climate_risk', 'climate_hazard_other')
    # ### end Alembic commands ###
