"""empty message

Revision ID: a98b786dc0de
Revises: 2893776a399e
Create Date: 2021-07-13 15:29:08.928385

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a98b786dc0de'
down_revision = '2893776a399e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_activity', sa.Column(
        'fund_source', sa.String(length=30), nullable=False))
    op.add_column('me_output', sa.Column(
        'challenges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_output', 'challenges')
    op.drop_column('me_activity', 'fund_source')
    # ### end Alembic commands ###
