"""empty message

Revision ID: abf1b61d9cfe
Revises: d4e337c7cc14
Create Date: 2021-02-27 01:42:38.099305

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abf1b61d9cfe'
down_revision = 'd4e337c7cc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'ndp_strategies', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'ndp_strategies')
    # ### end Alembic commands ###
