"""empty message

Revision ID: ac7f7fcc9111
Revises: 83032d1ab6a8
Create Date: 2020-08-14 00:49:36.607157

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac7f7fcc9111'
down_revision = '83032d1ab6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column(
        'permission_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'permission_config')
    # ### end Alembic commands ###
