"""empty message

Revision ID: ad83492d097f
Revises: d7a9c57e9ac0
Create Date: 2020-08-17 20:49:29.920076

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad83492d097f'
down_revision = 'd7a9c57e9ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'code',
                    existing_type=mysql.VARCHAR(length=10),
                    type_=sa.String(length=20),
                    existing_nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'code',
                    existing_type=sa.String(length=20),
                    type_=mysql.VARCHAR(length=10),
                    existing_nullable=False)
    # ### end Alembic commands ###
