"""empty message

Revision ID: aff2b0eabc8c
Revises: d26c18a1161b
Create Date: 2020-06-22 23:10:53.609812

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aff2b0eabc8c'
down_revision = 'd26c18a1161b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column(
        'workflow_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'instance_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'workflow_config')
    op.drop_column('instance', 'instance_config')
    # ### end Alembic commands ###
