"""empty message

Revision ID: b032c815191c
Revises: ffb7f569b48c
Create Date: 2021-01-21 01:22:19.819951

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b032c815191c'
down_revision = 'ffb7f569b48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'fund_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'fund_ids', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
