"""empty message

Revision ID: b218ed37b3d9
Revises: 72a3c995869c
Create Date: 2021-12-01 16:26:00.419296

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b218ed37b3d9'
down_revision = '72a3c995869c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'sector_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'sector_ids')
    # ### end Alembic commands ###
