"""empty message

Revision ID: b2d4f33ca29b
Revises: 1e7848665239
Create Date: 2021-03-17 20:43:22.369184

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2d4f33ca29b'
down_revision = '1e7848665239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment', sa.Column(
        'financial_pattern_subtype', sa.SmallInteger(), nullable=True))
    op.add_column('investment', sa.Column(
        'financial_pattern_type', sa.SmallInteger(), nullable=True))
    op.add_column('investment', sa.Column(
        'fund_body_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment', 'fund_body_type')
    op.drop_column('investment', 'financial_pattern_type')
    op.drop_column('investment', 'financial_pattern_subtype')
    # ### end Alembic commands ###
