"""empty message

Revision ID: b3b9b83595c7
Revises: 56561aac764a
Create Date: 2020-09-20 01:24:42.820250

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b9b83595c7'
down_revision = '56561aac764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('phase_ids', sa.JSON(), nullable=True))
    op.execute("UPDATE role SET phase_ids = '[1,2,3]'")
    op.alter_column('role', 'phase_ids',
                    existing_type=mysql.JSON(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'phase_ids')
    # ### end Alembic commands ###
