"""empty message

Revision ID: b44babb50aea
Revises: 1f57ff5c1da2
Create Date: 2021-05-31 23:45:27.152188

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b44babb50aea'
down_revision = '1f57ff5c1da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'funding_modality',
                    existing_type=mysql.ENUM(
                        'PARTNERSHIP', 'PROCUREMENT', 'JOINT_VENTURE', 'UNSOLICITED_PROPOSAL'),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'funding_modality',
                    existing_type=sa.String(length=255),
                    type_=mysql.ENUM('PARTNERSHIP', 'PROCUREMENT',
                                     'JOINT_VENTURE', 'UNSOLICITED_PROPOSAL'),
                    existing_nullable=True)
    # ### end Alembic commands ###
