"""empty message

Revision ID: b88c4cd789c3
Revises: 2a012fc9d059
Create Date: 2021-03-31 17:54:17.082883

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b88c4cd789c3'
down_revision = '2a012fc9d059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'budget_allocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'budget_allocation', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
