"""empty message

Revision ID: bbcfd58bb8ff
Revises: b6731a70f3a5
Create Date: 2021-10-03 23:38:08.236750

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbcfd58bb8ff'
down_revision = 'b6731a70f3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('myc_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'myc_data')
    # ### end Alembic commands ###
