"""empty message

Revision ID: bc7c0a332bc5
Revises: a98b786dc0de
Create Date: 2021-07-14 17:53:09.182735

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc7c0a332bc5'
down_revision = 'a98b786dc0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'methodology', sa.Text(), nullable=True))
    op.add_column('me_report', sa.Column(
        'rational_study', sa.Text(), nullable=True))
    op.add_column('me_report', sa.Column('summary', sa.Text(), nullable=True))
    op.alter_column('me_report', 'issues',
                    existing_type=mysql.TEXT(),
                    type_=sa.JSON(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'me_report', type_='foreignkey')
    op.drop_constraint(None, 'me_report', type_='foreignkey')
    op.drop_constraint(None, 'me_report', type_='foreignkey')
    op.alter_column('me_report', 'issues',
                    existing_type=sa.JSON(),
                    type_=mysql.TEXT(),
                    existing_nullable=True)
    # ### end Alembic commands ###
