"""empty message

Revision ID: bf761d716de6
Revises: 0ad6be19b8a9
Create Date: 2021-03-13 23:17:43.690276

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf761d716de6'
down_revision = '0ad6be19b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('program_code_unq', 'program', ['code'])
    op.create_unique_constraint('program_name_unq', 'program', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('program_name_unq', 'program', type_='unique')
    op.drop_constraint('program_code_unq', 'program', type_='unique')
    # ### end Alembic commands ###
