"""empty message

Revision ID: c21b2692d35f
Revises: de82fcac5c19
Create Date: 2020-09-15 23:43:25.347282

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c21b2692d35f'
down_revision = 'de82fcac5c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'score',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_option', 'score',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    # ### end Alembic commands ###
