"""empty message

Revision ID: c52ce8c68a05
Revises: f0a5049780aa
Create Date: 2021-06-27 14:17:57.133360

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c52ce8c68a05'
down_revision = 'f0a5049780aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'current_step', sa.SmallInteger(), nullable=False))
    op.add_column('me_report', sa.Column(
        'max_step', sa.SmallInteger(), nullable=False))
    op.add_column('me_report', sa.Column(
        'me_workflow_id', sa.Integer(), nullable=False))
    op.execute(
        "UPDATE me_report SET current_step = 1, max_step=1, me_workflow_id=1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_report', 'me_workflow_id')
    op.drop_column('me_report', 'max_step')
    op.drop_column('me_report', 'current_step')
    # ### end Alembic commands ###
