"""empty message

Revision ID: c5514de47925
Revises: c21b2692d35f
Create Date: 2020-09-16 12:33:26.198839

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5514de47925'
down_revision = 'c21b2692d35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_evaluation', sa.Column(
        'criteria', sa.JSON(), nullable=True))
    op.add_column('financial_evaluation', sa.Column(
        'criteria', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_evaluation', 'criteria')
    op.drop_column('economic_evaluation', 'criteria')
    # ### end Alembic commands ###
