"""empty message

Revision ID: c6a9b8765923
Revises: 77fa8923fea8
Create Date: 2020-09-14 14:57:24.725725

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6a9b8765923'
down_revision = '77fa8923fea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('output', sa.Column('investments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('output', 'investments')
    # ### end Alembic commands ###
