"""empty message

Revision ID: c6c7e56fe844
Revises: 9b712207656e
Create Date: 2021-03-03 01:52:20.556968

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6c7e56fe844'
down_revision = '9b712207656e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column(
        'file_type_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'file_type_ids')
    # ### end Alembic commands ###
