"""empty message

Revision ID: ca0ccae4a887
Revises: 6a9ea7f6c2ca
Create Date: 2021-03-01 03:18:15.245791

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca0ccae4a887'
down_revision = '6a9ea7f6c2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'governance', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_compliance', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_policy_alignment', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ndp_sustainable_goals', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'risk_assessment', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ppp_interest', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ppp_impediments', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ppp_risk_allocation', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'ppp_similar_reference', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'procurement_modality', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'revenue_source', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'default_option_name', sa.String(length=255), nullable=True))
    op.add_column('project_detail', sa.Column(
        'default_option_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'default_option_description')
    op.drop_column('project_detail', 'default_option_name')
    op.drop_column('project_detail', 'revenue_source')
    op.drop_column('project_detail', 'procurement_modality')
    op.drop_column('project_detail', 'ppp_similar_reference')
    op.drop_column('project_detail', 'ppp_risk_allocation')
    op.drop_column('project_detail', 'ppp_impediments')
    op.drop_column('project_detail', 'ppp_interest')
    op.drop_column('project_detail', 'risk_assessment')
    op.drop_column('project_detail', 'ndp_sustainable_goals')
    op.drop_column('project_detail', 'ndp_policy_alignment')
    op.drop_column('project_detail', 'ndp_compliance')
    op.drop_column('project_detail', 'governance')
    # ### end Alembic commands ###
