"""empty message

Revision ID: cc59d5847814
Revises: 5ce68c76aeb7
Create Date: 2020-09-18 17:45:49.851097

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc59d5847814'
down_revision = '5ce68c76aeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column(
        'output_id', sa.Integer(), nullable=True))
    op.create_foreign_key("activity_output_id_ibfk",
                          'activity', 'output', ['output_id'], ['id'])
    op.drop_column('activity', 'output_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column(
        'output_ids', mysql.JSON(), nullable=True))
    op.drop_constraint("activity_output_id_ibfk",
                       'activity', type_='foreignkey')
    op.drop_column('activity', 'output_id')
    # ### end Alembic commands ###
