"""empty message

Revision ID: cf92ecf3d2b9
Revises: 99975ec08b29
Create Date: 2021-01-12 03:09:01.729241

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf92ecf3d2b9'
down_revision = '99975ec08b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'classification', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'classification')
    # ### end Alembic commands ###
