"""empty message

Revision ID: cff402fb7950
Revises: 987ad3723b52
Create Date: 2020-08-18 00:25:28.667800

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cff402fb7950'
down_revision = '987ad3723b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column(
        'costing_config', sa.JSON(), nullable=True))
    op.drop_column('instance', 'cost_config')
    op.drop_column('instance', 'class_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column(
        'class_config', mysql.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'cost_config', mysql.JSON(), nullable=True))
    op.drop_column('instance', 'costing_config')
    # ### end Alembic commands ###
