"""empty message

Revision ID: d26c18a1161b
Revises:
Create Date: 2020-06-22 22:55:27.003838

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd26c18a1161b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column(
        'class_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'cost_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'fund_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'location_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'organization_config', sa.JSON(), nullable=True))
    op.add_column('instance', sa.Column(
        'program_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'program_config')
    op.drop_column('instance', 'organization_config')
    op.drop_column('instance', 'location_config')
    op.drop_column('instance', 'fund_config')
    op.drop_column('instance', 'cost_config')
    op.drop_column('instance', 'class_config')
    # ### end Alembic commands ###
