"""empty message

Revision ID: d3ff4573dfb0
Revises: 9a760150eecd
Create Date: 2020-09-17 15:12:19.777898

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3ff4573dfb0'
down_revision = '9a760150eecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'plan_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'plan_details')
    # ### end Alembic commands ###
