"""empty message

Revision ID: d42ffb67c70f
Revises: 64d4b130bd12
Create Date: 2021-04-12 00:42:20.997743

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd42ffb67c70f'
down_revision = '64d4b130bd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program', 'organization_ids',
                    existing_type=sa.String(length=255),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program', 'organization_ids',
                    existing_type=sa.Text(),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
