"""empty message

Revision ID: d4e337c7cc14
Revises: 7dabfa08d067
Create Date: 2021-02-01 03:15:35.981418

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4e337c7cc14'
down_revision = '7dabfa08d067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column(
        'delegated_by', sa.Integer(), nullable=True))
    op.add_column('user_role', sa.Column('is_delegator', sa.Boolean(),
                                         server_default=sa.text('false'), nullable=False))
    op.create_foreign_key("user_role_delegator_idx",
                          'user_role', 'user', ['delegated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_role_delegator_idx',
                       'user_role', type_='foreignkey')
    op.drop_column('user_role', 'is_delegator')
    op.drop_column('user_role', 'delegated_by')
    # ### end Alembic commands ###
