"""empty message

Revision ID: d7a9c57e9ac0
Revises: ac7f7fcc9111
Create Date: 2020-08-17 18:07:55.957977

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7a9c57e9ac0'
down_revision = 'ac7f7fcc9111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature', 'created_by')
    op.drop_column('feature', 'modified_on')
    op.drop_column('feature', 'modified_by')
    op.drop_column('feature', 'created_on')
    op.drop_column('instance', 'created_by')
    op.drop_column('instance', 'modified_on')
    op.drop_column('instance', 'modified_by')
    op.drop_column('instance', 'created_on')
    op.drop_column('module', 'created_by')
    op.drop_column('module', 'modified_on')
    op.drop_column('module', 'modified_by')
    op.drop_column('module', 'created_on')
    op.drop_column('permission', 'created_by')
    op.drop_column('permission', 'modified_on')
    op.drop_column('permission', 'modified_by')
    op.drop_column('permission', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column(
        'created_on', mysql.DATETIME(), nullable=True))
    op.add_column('permission', sa.Column('modified_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.add_column('permission', sa.Column(
        'modified_on', mysql.DATETIME(), nullable=True))
    op.add_column('permission', sa.Column('created_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.add_column('module', sa.Column(
        'created_on', mysql.DATETIME(), nullable=True))
    op.add_column('module', sa.Column('modified_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.add_column('module', sa.Column(
        'modified_on', mysql.DATETIME(), nullable=True))
    op.add_column('module', sa.Column('created_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.add_column('instance', sa.Column(
        'created_on', mysql.DATETIME(), nullable=True))
    op.add_column('instance', sa.Column('modified_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.add_column('instance', sa.Column(
        'modified_on', mysql.DATETIME(), nullable=True))
    op.add_column('instance', sa.Column('created_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    op.add_column('feature', sa.Column(
        'created_on', mysql.DATETIME(), nullable=True))
    op.add_column('feature', sa.Column('modified_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.add_column('feature', sa.Column(
        'modified_on', mysql.DATETIME(), nullable=True))
    op.add_column('feature', sa.Column('created_by', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
