"""empty message

Revision ID: de82fcac5c19
Revises: 8ab32a9925af
Create Date: 2020-09-15 23:03:55.258608

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de82fcac5c19'
down_revision = '8ab32a9925af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('economic_evaluation', 'enpv',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('economic_evaluation', 'err',
                    existing_type=mysql.VARCHAR(length=6),
                    nullable=True)
    op.alter_column('financial_evaluation', 'fnpv',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('financial_evaluation', 'irr',
                    existing_type=mysql.VARCHAR(length=6),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_evaluation', 'irr',
                    existing_type=mysql.VARCHAR(length=6),
                    nullable=False)
    op.alter_column('financial_evaluation', 'fnpv',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    op.alter_column('economic_evaluation', 'err',
                    existing_type=mysql.VARCHAR(length=6),
                    nullable=False)
    op.alter_column('economic_evaluation', 'enpv',
                    existing_type=mysql.VARCHAR(length=20),
                    nullable=False)
    # ### end Alembic commands ###
