"""empty message

Revision ID: e2a637309d09
Revises: c52ce8c68a05
Create Date: 2021-06-28 14:32:38.847447

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2a637309d09'
down_revision = 'c52ce8c68a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'frequency', sa.String(length=255), nullable=False))
    op.execute("UPDATE me_report SET frequency = 'ANNUAL'")
    op.drop_column('me_activity', 'next_budget_appropriation')
    op.alter_column('me_activity', 'activity_status',
                    existing_type=mysql.ENUM(
                        'ON_TRACK', 'COMPLETED', 'DELAYED'),
                    type_=sa.Enum('ON_TRACK', 'COMPLETED', 'DELAYED', 'SATISFACTORY', 'NOT_SATISFACTORY',
                                  'MODERATELY_SATISFACTORY', 'NO_ASSESSMENT', name='activitystatus'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('me_activity', 'activity_status',
                    existing_type=mysql.ENUM('ON_TRACK', 'COMPLETED', 'DELAYED', 'SATISFACTORY', 'NOT_SATISFACTORY',
                                             'MODERATELY_SATISFACTORY', 'NO_ASSESSMENT'),
                    type_=sa.Enum('ON_TRACK', 'COMPLETED',
                                  'DELAYED', name='activitystatus'),
                    existing_nullable=False)
    op.drop_column('me_report', 'frequency')
    op.add_column('me_activity', sa.Column(
        'next_budget_appropriation', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###
