"""empty message

Revision ID: e7d40e4b5a5d
Revises: 11c4429212ed
Create Date: 2021-06-24 10:24:30.153358

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7d40e4b5a5d'
down_revision = '11c4429212ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_activity', sa.Column(
        'budget_supplemented', sa.String(length=20), nullable=True))
    op.add_column('me_report', sa.Column(
        'disbursement', sa.Text(), nullable=False))
    op.add_column('me_report', sa.Column(
        'effectiveness_date', sa.Date(), nullable=True))
    op.add_column('me_report', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('me_report', sa.Column(
        'signed_date', sa.Date(), nullable=True))
    op.add_column('me_report', sa.Column(
        'start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_report', 'start_date')
    op.drop_column('me_report', 'signed_date')
    op.drop_column('me_report', 'end_date')
    op.drop_column('me_report', 'effectiveness_date')
    op.drop_column('me_report', 'disbursement')
    op.drop_column('me_activity', 'budget_supplemented')
    # ### end Alembic commands ###
