"""empty message

Revision ID: e92b64911669
Revises: 295f141799cf
Create Date: 2020-08-27 23:40:20.724857

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e92b64911669'
down_revision = '295f141799cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization',
                          ['organization_id'], ['id'])
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'roles', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    # ### end Alembic commands ###
