"""empty message

Revision ID: ead4b1a7967c
Revises: 14ab8ef70254
Create Date: 2021-11-11 14:58:18.733897

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead4b1a7967c'
down_revision = '14ab8ef70254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'ranking_score',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'ranking_score',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    # ### end Alembic commands ###
