"""empty message

Revision ID: eb0b0fc49743
Revises: fe5e5dd30620
Create Date: 2020-09-17 16:17:19.299825

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb0b0fc49743'
down_revision = 'fe5e5dd30620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE project SET current_step = 1")
    op.alter_column('project', 'current_step',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'current_step',
                    existing_type=mysql.SMALLINT(display_width=6),
                    nullable=True)
    # ### end Alembic commands ###
