"""empty message

Revision ID: eb5f596917eb
Revises: 1faccb575e31
Create Date: 2021-05-04 20:01:58.102116

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb5f596917eb'
down_revision = '1faccb575e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'submission_date', sa.DateTime(), nullable=True))
    op.execute("update project p INNER JOIN timeline t ON t.workflow_id=1 and p.phase_id=t.phase_id and t.project_id=p.id set submission_date = t.created_on")
    op.execute("update project p INNER JOIN timeline t ON t.workflow_id=1 and p.phase_id-1=t.phase_id and t.project_id=p.id set submission_date = t.created_on where p.submission_date is null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'submission_date')
    # ### end Alembic commands ###
