"""empty message

Revision ID: ecf737574579
Revises: b5925f573164
Create Date: 2022-05-03 09:34:10.766977

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecf737574579'
down_revision = 'b5925f573164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'behavior_knowledge_products', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'behavior_measures', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'behavior_project_results', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'national_scope', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'procurement_plan_description', sa.Text(), nullable=True))
    op.add_column('project_detail', sa.Column(
        'work_plan_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'work_plan_description')
    op.drop_column('project_detail', 'procurement_plan_description')
    op.drop_column('project_detail', 'national_scope')
    op.drop_column('project_detail', 'behavior_project_results')
    op.drop_column('project_detail', 'behavior_measures')
    op.drop_column('project_detail', 'behavior_knowledge_products')
    # ### end Alembic commands ###
