"""empty message

Revision ID: f0a5049780aa
Revises: 5c87c68bde5d
Create Date: 2021-06-25 20:11:33.547350

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0a5049780aa'
down_revision = '5c87c68bde5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('me_report', sa.Column(
        'challenges', sa.Text(), nullable=True))
    op.add_column('me_report', sa.Column('issues', sa.Text(), nullable=True))
    op.add_column('me_report', sa.Column(
        'lessons_learned', sa.Text(), nullable=True))
    op.add_column('me_report', sa.Column(
        'recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('me_report', 'recommendations')
    op.drop_column('me_report', 'lessons_learned')
    op.drop_column('me_report', 'issues')
    op.drop_column('me_report', 'challenges')
    # ### end Alembic commands ###
