"""empty message

Revision ID: f43dd953e863
Revises: 0a10f52358f1
Create Date: 2021-04-14 23:13:11.752382

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f43dd953e863'
down_revision = '0a10f52358f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costing', sa.Column('is_capital', sa.Boolean(),
                                       server_default=sa.text('false'), nullable=False))
    op.execute("UPDATE costing SET is_capital = true where id in (10,11,12,13)")
    op.execute(
        "UPDATE costing SET is_capital = true where parent_id in (10,11,12,13)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costing', 'is_capital')
    # ### end Alembic commands ###
