"""empty message

Revision ID: f67bed7b31ec
Revises: b88c4cd789c3
Create Date: 2021-04-06 21:37:31.035899

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f67bed7b31ec'
down_revision = 'b88c4cd789c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('program_code_unq', table_name='program')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('program_code_unq', 'program', ['code'], unique=True)
    # ### end Alembic commands ###
