"""empty message

Revision ID: fb96610ccce9
Revises: f43dd953e863
Create Date: 2021-04-22 02:37:53.140158

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb96610ccce9'
down_revision = 'f43dd953e863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
                    existing_type=mysql.VARCHAR(length=50),
                    nullable=False)
    # ### end Alembic commands ###
