"""empty message

Revision ID: fe5e5dd30620
Revises: d3ff4573dfb0
Create Date: 2020-09-17 16:05:16.692615

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe5e5dd30620'
down_revision = 'd3ff4573dfb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'current_step', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'current_step')
    # ### end Alembic commands ###
