"""empty message

Revision ID: ffb7f569b48c
Revises: 963ee01b5678
Create Date: 2021-01-17 00:56:51.259452

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffb7f569b48c'
down_revision = '963ee01b5678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_detail', sa.Column(
        'fund_ids', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_detail', 'fund_ids')
    # ### end Alembic commands ###
